# Generated by Django 4.2.9 on 2026-04-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=100, unique=True)),
                ('val_id', models.CharField(blank=True, max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('status', models.CharField(
                    choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('verified', 'Verified / Successful'),
                             ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')],
                    default='initiated', max_length=15)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment',
                                                 to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
